# Form implementation generated from reading ui file 'RegisterPrestamo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 249)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(10, 10, 422, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 59, 381, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lb_nombre = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lb_nombre.setObjectName("lb_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lb_nombre)
        self.le_codEquipo = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.le_codEquipo.setObjectName("le_codEquipo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_codEquipo)
        self.lblApellidoPA = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblApellidoPA.setObjectName("lblApellidoPA")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblApellidoPA)
        self.le_codCliente = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.le_codCliente.setObjectName("le_codCliente")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_codCliente)
        self.lblFechaNac = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblFechaNac.setObjectName("lblFechaNac")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFechaNac)
        self.de_fechaDev = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.de_fechaDev.setObjectName("de_fechaDev")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.de_fechaDev)
        self.lb_email = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lb_email.setObjectName("lb_email")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lb_email)
        self.cb_estado = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.cb_estado.setObjectName("cb_estado")
        self.cb_estado.addItem("")
        self.cb_estado.addItem("")
        self.cb_estado.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cb_estado)
        self.lb_prestamo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_prestamo.setGeometry(QtCore.QRect(40, 40, 59, 16))
        self.lb_prestamo.setObjectName("lb_prestamo")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 190, 381, 37))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnRegistrar = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.btnRegistrar.setMinimumSize(QtCore.QSize(150, 35))
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.horizontalLayout_3.addWidget(self.btnRegistrar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AÑADIR CLIENTES"))
        self.lblTitulo.setText(_translate("MainWindow", "REGISTRAR"))
        self.lb_nombre.setText(_translate("MainWindow", "Codigo equipo*"))
        self.lblApellidoPA.setText(_translate("MainWindow", "Codigo cliente*"))
        self.lblFechaNac.setText(_translate("MainWindow", "Fecha Dev*"))
        self.lb_email.setText(_translate("MainWindow", "Estado"))
        self.cb_estado.setItemText(0, _translate("MainWindow", "Prestado"))
        self.cb_estado.setItemText(1, _translate("MainWindow", "Devuelto"))
        self.cb_estado.setItemText(2, _translate("MainWindow", "Atrasado"))
        self.lb_prestamo.setText(_translate("MainWindow", "PRESTAMO"))
        self.btnRegistrar.setText(_translate("MainWindow", "Registrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
    MainWindow.show()
    sys.exit(app.exec())
