# Form implementation generated from reading ui file 'RegisterAtt_S.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_superior)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lb_tituloPagina = QtWidgets.QLabel(parent=self.frame_superior)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.lb_tituloPagina.setFont(font)
        self.lb_tituloPagina.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_tituloPagina.setObjectName("lb_tituloPagina")
        self.verticalLayout_4.addWidget(self.lb_tituloPagina)
        self.frame = QtWidgets.QFrame(parent=self.frame_superior)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_formulario = QtWidgets.QFrame(parent=self.frame)
        self.frame_formulario.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_formulario.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_formulario.setObjectName("frame_formulario")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_formulario)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, -1)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_codigo = QtWidgets.QLabel(parent=self.frame_formulario)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_codigo.setFont(font)
        self.lb_codigo.setObjectName("lb_codigo")
        self.verticalLayout_3.addWidget(self.lb_codigo)
        self.le_codigo = QtWidgets.QLineEdit(parent=self.frame_formulario)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_codigo.setFont(font)
        self.le_codigo.setObjectName("le_codigo")
        self.verticalLayout_3.addWidget(self.le_codigo)
        self.bt_aceptar = QtWidgets.QPushButton(parent=self.frame_formulario)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_aceptar.setFont(font)
        self.bt_aceptar.setObjectName("bt_aceptar")
        self.verticalLayout_3.addWidget(self.bt_aceptar)
        self.horizontalLayout.addWidget(self.frame_formulario)
        spacerItem1 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_inferior.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_inferior)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_avatar = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_avatar.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_avatar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_avatar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_avatar.setObjectName("frame_avatar")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_avatar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_avatar = QtWidgets.QLabel(parent=self.frame_avatar)
        self.verticalLayout_2.addWidget(self.frame_avatar)
        self.frame_info = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_info.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_info)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lb_nombre = QtWidgets.QLabel(parent=self.frame_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.lb_nombre.setFont(font)
        self.lb_nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_nombre.setObjectName("lb_nombre")
        self.verticalLayout_5.addWidget(self.lb_nombre)
        self.lb_info = QtWidgets.QLabel(parent=self.frame_info)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_info.setFont(font)
        self.lb_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_info.setObjectName("lb_info")
        self.verticalLayout_5.addWidget(self.lb_info)
        self.verticalLayout_2.addWidget(self.frame_info)
        self.verticalLayout.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Configuraciones adicionales
        try:
            lbl = self.lb_avatar
        except AttributeError:
            lbl = QtWidgets.QLabel(parent=self.frame_avatar)
            self.lb_avatar = lbl

        lbl.setFixedSize(300, 300)
        lbl.setText("")
        lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        ruta_actual = os.path.dirname(os.path.abspath(__file__))
        ruta_imagen = os.path.join(ruta_actual, "ICONS", "avatar-icon.png")
        pix = QtGui.QPixmap(ruta_imagen)
        if not pix.isNull():
            pix = pix.scaled(300, 300, QtCore.Qt.AspectRatioMode.KeepAspectRatio, QtCore.Qt.TransformationMode.SmoothTransformation)
            lbl.setPixmap(pix)
        else:
            lbl.setText("No image")

        lbl.setObjectName("lb_avatar")
        try:
            self.gridLayout.addWidget(lbl, 0, 0, QtCore.Qt.AlignmentFlag.AlignCenter)
        except Exception:
            try:
                self.frame_avatar.layout().addWidget(lbl)
            except Exception:
                pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_tituloPagina.setText(_translate("MainWindow", "Registro de Asistencia"))
        self.lb_codigo.setText(_translate("MainWindow", "Codigo:"))
        self.bt_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.lb_nombre.setText(_translate("MainWindow", "Nombre"))
        self.lb_info.setText(_translate("MainWindow", "Informacion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    #Evitamos que la ventana sea redimensionable
    MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
    MainWindow.show()
    sys.exit(app.exec())
